### ISSUE TITLE
KeyError in line 58 of Snakefile-hifimags.smk: 'completeness_aware'

### ISSUE THREAD

**Issue by cho7-31** [PacificBiosciences/pb-metagenomics-tools#63]
Please leave the headers below and replace the relevant text. This will expedite addressing the ticket. 

Hello, I have a problem that I describe below:

**Name the workflow**
I'm using HiFi-MAG-Pipeline last version in master branch

**Describe the bug**
When I try to launch the workflow I obtain immediatly the folowing error : 
KeyError in line 58 of Snakefile-hifimags.smk: 'completeness_aware'

**Expected behavior**
In the config.yaml I have the folowwing text : 
# The settings below will affect the completeness-aware binning step.
completeness_aware:
  # Minimum size of a contig to consider for completeness scores. The default value is set to 500kb.
  # This value should NOT be increased. It could be decreased, but genomes <500kb are not expected and
  # contigs this size will likely fail the completeness filtering.
  min_length: 500000

  # Minimum completeness score (from CheckM2) to mark a contig as "complete" and place
  # it in a distinct bin. This should not be lowered below 90.
  min_completeness: 93

So I do not understand why completeness_aware is not recognized.

**Screenshots**
If applicable, add screenshots to help explain your problem. There is on-screen error reporting in the snakemake execution and it can be helpful to include this here.

**Log files**
I don't have logs files yet.

Thanks a lot for your help !

**Comment by dportik** [comment]
Hi @cho7-31 ,
I have not encountered this error before. It is possible your `config.yaml` is not formatted correctly. It should include a two space indent for the items nested under `completeness_aware`:

```
# The settings below will affect the completeness-aware binning step.
completeness_aware:
  # Minimum size of a contig to consider for completeness scores. The default value is set to 500kb.
  # This value should NOT be increased. It could be decreased, but genomes <500kb are not expected and
  # contigs this size will likely fail the completeness filtering.
  min_length: 500000

  # Minimum completeness score (from CheckM2) to mark a contig as "complete" and place 
  # it in a distinct bin. This should not be lowered below 90.
  min_completeness: 93
```

Can you attach your `config.yaml` file here so we can check this? It will help rule out some potential causes.
